### ISSUE TITLE
Enable/disable feature for test execution based on Android version

### ISSUE THREAD

**Issue by philippkumar** [techatspree/android-marvin#2]
Certain Tests run successful in 2.2, but fail in 2.1 and 1.6.
Example is a SecurityException (event injection not allowed).

An annotation to control, on which Android versions the test shall run, would be nice.

**Comment by ebiermann** [comment]
A test-by-test switch  to disable a test for certain version can be done like this:
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.HONEYCOMB) return;

An annotation to handle this on a class or test basis without touching a specific test would require the test runner to be aware of this annotation. This would require Marvin to replace/extend the default InstrumentationTestRunner of Android.

Though probably possible, this is outside the scope of Marvin at the moment.
